### ISSUE TITLE
[Feature] Implement 'ip-hash' mode for load balancer

### ISSUE THREAD

**Issue by xiaoyang-sde** [booster-labs/rocket-booster#114]
Currently, the load balancer only supports 'random' mode: Given a group of upstream server, it randomly picks an upstream to send the request.

The 'ip-hash' mode determines the server to which a request is sent from the client IP address. The method guarantees that requests from the same address get to the same server.

For example, the client IP address is `127.0.0.1` and its hash value is `127000000001`. If there are 3 upstream servers, the load balancer will pick **the third** server since `127000000001 % 3 = 2`.

**Comment by lorenzoc25** [comment]
#129
