### ISSUE TITLE
WebSocket is failed

### ISSUE THREAD

**Issue by ZhaoUncle** [booster-labs/rocket-booster#97]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug.

**Screenshots**

**Additional context**

**Comment by xiaoyang-sde** [comment]
Thanks! I will fix it asap.

**Comment by xiaoyang-sde** [comment]
Fixed in #98

**Comment by ZhaoUncle** [comment]
Thank you very much, I will try to verify it after I release the new version tomorrow

**Comment by xiaoyang-sde** [comment]
> Thank you very much, I will try to verify it after I release the new version tomorrow

Sorry for the delay, but I finally published the new version :rocket:
